# configuration file for dotnet-releaser
[msbuild]
project = "SharpYaml.sln"
[github]
user = "xoofx"
repo = "SharpYaml"
branches = ["v2_security_fixes_only"]
[nuget]
user = "xoofx"
trusted_publishing = true
