name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - '*.md'
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      actions: write
      contents: write
    runs-on: 'windows-latest'
    steps:
      - name: "Build, Test, Pack and Publish"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main